# Generated by Django 2.1.5 on 2019-10-24 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.CharField(choices=[('1', '服务器'), ('2', '路由器'), ('3', '交换机'), ('4', '防火墙')], default='1', help_text='服务器类型', max_length=1)),
                ('device_status_id', models.CharField(choices=[('1', '上架'), ('2', '在线'), ('3', '离线'), ('4', '下架')], default='1', help_text='服务器状态', max_length=1)),
                ('cabinet_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜中序号')),
                ('latest_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='机柜编号')),
                ('cab_lever', models.CharField(max_length=2, verbose_name='U 数')),
            ],
            options={
                'verbose_name_plural': '机柜表',
                'db_table': 'cabinet',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreced', models.CharField(max_length=200, null=True, verbose_name='强制磁盘容量')),
                ('pd', models.CharField(max_length=10, null=True, verbose_name='接口类型')),
                ('raw', models.CharField(max_length=200, null=True, verbose_name='原始磁盘容量')),
                ('slot', models.CharField(max_length=10, null=True, verbose_name='插槽号')),
            ],
            options={
                'verbose_name': '硬盘表',
                'verbose_name_plural': '硬盘表',
                'db_table': 'disk',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='机房')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '机房表',
                'db_table': 'idc',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=100, null=True, verbose_name='内存容量')),
                ('slot', models.CharField(max_length=128, null=True, verbose_name='插槽')),
                ('model', models.CharField(max_length=128, null=True, verbose_name='内存类型')),
                ('speed', models.CharField(max_length=128, null=True, verbose_name='速率')),
                ('manufacturer', models.CharField(max_length=128, null=True, verbose_name='内存厂商')),
                ('sn', models.CharField(max_length=128, null=True, verbose_name='产品序列号')),
            ],
            options={
                'verbose_name_plural': '内存表',
                'db_table': 'memory',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=520, verbose_name='操作系统')),
                ('machine', models.CharField(max_length=520, verbose_name='系统架构')),
                ('host_name', models.CharField(max_length=520, verbose_name='主机名')),
                ('os_version', models.CharField(max_length=520, verbose_name='系统版本')),
                ('kernel', models.CharField(max_length=520, verbose_name='内核信息')),
                ('model_name', models.CharField(max_length=520, verbose_name='cpu名称')),
                ('cpu_type', models.CharField(max_length=520, verbose_name='cpu类型')),
                ('physical_count', models.IntegerField(verbose_name='cpu物理颗数')),
                ('cpu_cores', models.IntegerField(verbose_name='每颗cpu核心数')),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='cmdb.Asset', verbose_name='资产')),
            ],
            options={
                'verbose_name_plural': '服务器表',
                'db_table': 'server',
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='cmdb.Server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='cmdb.Server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cabinet',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='机柜号'),
        ),
    ]
