# Generated by Django 2.1.5 on 2019-10-28 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签')),
                ('latest_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签信息表',
                'verbose_name_plural': '标签信息表',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('node_upstream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_node', to='cmdb.TreeNode', verbose_name='上级节点')),
            ],
            options={
                'verbose_name': '服务树节点表',
                'verbose_name_plural': '服务树节点表',
                'db_table': 'tree_node',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='latest_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='disk',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='disk',
            name='latest_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='idc',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='idc',
            name='latest_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='memory',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='memory',
            name='latest_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='server',
            name='latest_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='asset',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='cmdb.TreeNode', verbose_name='节点'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(related_name='assets', to='cmdb.Tag', verbose_name='标签'),
        ),
    ]
