# Generated by Django 2.1.5 on 2019-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191028_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='ssh用户')),
                ('password', models.CharField(max_length=1024, verbose_name='连接密码')),
                ('port', models.PositiveSmallIntegerField()),
                ('authed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='manager_ip',
            field=models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='connetion',
            name='server',
            field=models.ManyToManyField(related_name='conn', to='cmdb.Server', verbose_name='所属服务器'),
        ),
    ]
