# Generated by Django 2.1.5 on 2019-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20191031_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='ssh用户')),
                ('password', models.CharField(max_length=1024, verbose_name='连接密码')),
                ('port', models.PositiveSmallIntegerField(verbose_name='sshd 监听端口')),
                ('authed', models.BooleanField(default=False, help_text='是否建立了基于密钥的信任关系', verbose_name='是否认证')),
                ('server', models.ManyToManyField(related_name='connection', to='cmdb.Server', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '服务器连接表',
                'verbose_name_plural': '服务器连接表',
                'db_table': 'connection',
            },
        ),
        migrations.RemoveField(
            model_name='connetion',
            name='server',
        ),
        migrations.DeleteModel(
            name='Connetion',
        ),
    ]
