# Generated by Django 2.1.5 on 2019-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20191031_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.PositiveIntegerField(verbose_name='sshd 监听端口'),
        ),
    ]
