# Generated by Django 2.1.5 on 2019-10-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20191031_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='cmdb.Connection', verbose_name='连接信息'),
        ),
    ]
