# Generated by Django 2.1.5 on 2019-11-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20191031_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64, verbose_name='组名')),
                ('server', models.ManyToManyField(related_name='inventory', to='cmdb.Server', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': 'Ansible资产清单',
                'verbose_name_plural': 'Ansible资产清单',
                'db_table': 'inventory_pool',
            },
        ),
    ]
